site_name: Snippets
repo_url: https://github.com/LucasGoncSilva/snippets
repo_name: Github/snippets
edit_uri: edit/main/doc/docs/


theme:
  name: material
  language: pt-BR
  # TODO: favicon: fontawesome/solid/book-open
  font:
    text: Roboto Mono

  icon:
    logo: fontawesome/solid/book-open
    next: fontawesome/solid/arrow-right
    previous: fontawesome/solid/arrow-left
    top: fontawesome/solid/arrow-up
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-3
        name: Light/Dark Mode
      primary: green
      accent: green

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Light/Dark Mode
      primary: green
      accent: green

  features:
    - navigation.indexes
    - navigation.tabs  # TODO: confirm presence
    - navigation.top
    - toc.integrate  # TODO: confirm presence
    - header.autohide
    - navigation.footer
    - content.action.view
    # - content.action.edit
    - announce.dismiss


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details


plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      enabled: true
      enable_creation_date: true
      fallback_to_build_date: true
      locale: pt


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LucasGoncSilva/ONR_Testing
      name: GitHub do projeto

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/registrodeimoveis.onr/
      name: Instagram ONR

    - icon: fontawesome/brands/facebook
      link: https://facebook.com/registrodeimoveis.onr/
      name: Facebook ONR

    - icon: fontawesome/brands/linkedin
      link: https://br.linkedin.com/company/operador-nacional-do-registro-eletr%C3%B4nico-de-im%C3%B3veis-onr
      name: LinkedIn ONR

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@registrodeimoveiseletronico/videos
      name: YouTube ONR


copyright: No copyright 'cause no one supports me :(
